# Generated by Django 6.0.6 on 2026-06-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_dailyspending_category_alter_dailyspending_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyspending',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
